# Exercise 1: Genetic Algorithm
The Genetic Algorithm (GA) is a powerful optimization and search technique based on the principles of natural selection and genetics. This exercise is designed to provide a hands-on experience with the GA

### Basic Structure of the Genetic Algorithm:

- Step 1. **Initial Population Generation:** Start by creating an initial population of potential solutions.
- Step 2. **Fitness Evaluation:** Assess the fitness of each individual in the population to determine how well they solve the given problem.
- Step 3. **Selection of the Fittest Individuals:** Employ a selection process to choose the best-performing individuals from the current population for reproduction.
- Step 4. **Offspring Generation and Mutation Application:** Generate offspring through genetic operations like crossover and mutation, introducing new genetic variations.

### Iterative Process:
- Repeat Steps 2 to 4 iteratively until the algorithm converges on an optimal solution or reaches a predefined maximum number of generations. This iterative process allows the GA to evolve increasingly better solutions over time.

## Import libraries

In [20]:
import numpy as np

%run assets/utility.py
np.set_printoptions(precision=4, suppress=True) # for better printing

## Genetic Representation

The effectiveness of a Genetic Algorithm (GA) relies heavily on how solutions to the problem are represented. For this exercise, we'll use a discrete binary representation, encoding our phenotypes as sequences of binary digits (`0` or `1`). This approach simplifies the manipulation and evaluation of potential solutions within our genetic framework.

---
### **Assignment**
Implement the `generate_initial_population`-function generating our population matrix. Each field of our matrix or gene stores either `0` or `1` in our discrete binary representation. Randomly initiate the values of our initial population.

Your task is to implement the `generate_initial_population` function, which will initialize our population. This function should create a population matrix where each entry, or gene, is randomly set to either `0` or `1`, representing our discrete binary genotype encoding.

The resulting population should be structured as follows, with `n` representing the number of genes per offspring and `m` the total number of offspring:

|   | Gene 1   | Gene 2   | $\cdots$   | Gene n   |
|:---:|:---:|:---:|:---:|:---:|
| Offspring 1   | $\dots$  | $\dots$  |  $\dots$ |  $\dots$ |
| Offspring 2  | $\dots$  |  $\dots$ | $\dots$  |  $\dots$ |
| $\vdots$  | $\dots$ | $\dots$  | $\dots$  | $\dots$  |
| Offspring m  |  $\dots$ | $\dots$  |  $\dots$ | $\dots$  |

1. **Random Initialization:** Generate the initial values of our population matrix randomly to ensure a diverse starting point.
2. **Return Shape:** The function should return a population matrix with the specified shape, allowing for easy manipulation and evaluation in subsequent steps of the GA.

### **Hints**
NumPy offers efficient methods for generating random binary arrays, which can be utilized to initialize the population matrix:

- [`np.random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) can be used with parameters 0 and 2 to generate binary values.
- [`np.random.choice`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html) with choices `[0, 1]` provides an alternative method for binary generation.

You can either directly generate multi-dimensional arrays by using the `size`-parameters of NumPy or manually by using two nested `for`-loops.

---

In [21]:
def generate_initial_population(population_size, chromosome_length):
    population = ...
    return population

In [22]:
# Solution 1:
def generate_initial_population(population_size, chromosome_length):
    population = np.zeros((population_size, chromosome_length))
    
    chromosome = np.random.randint(0, 2, size=(chromosome_length,))
    for i in range(population_size):
        np.random.shuffle(chromosome) # shuffles in-place
        population[i,:] = chromosome
        
    return population

In [23]:
# Solution 2:
def generate_initial_population(population_size, chromosome_length):
    binary_values = [0, 1]
    probabilities = [0.5, 0.5]
    population = np.random.choice(binary_values, size=(population_size, chromosome_length), p=probabilities)

    return population

In [24]:
# Solution 3:
def generate_initial_population(population_size, chromosome_length):
    population = np.random.randint(0, 2, size=(population_size, chromosome_length))
    return population

In [25]:
# Test your function:
population_size = 8
chromosome_length = 5

population = generate_initial_population(population_size, chromosome_length)
print(f"Population: {population.shape}\n{population}")

Population: (8, 5)
[[1 0 0 0 1]
 [1 0 1 1 1]
 [1 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 1 1]
 [0 1 1 1 1]
 [1 1 1 1 0]
 [1 1 0 0 1]]


## Step 3: Select the best individuals from population with Tournament Selection

Tournament selection is a method used to select individuals for the next generation's parents or survivors within a genetic algorithm. This method is effective for maintaining genetic diversity while favoring individuals with higher fitness.

### Steps for tournament selection:
1. **Random Selection:** Randomly select $k$ individuals from the population to participate in the tournament.
2. **Determine the Winner:** Evaluate the fitness of these $k$ individuals and select the one with the highest fitness as the winner of the tournament.
3. **Return Individuals:** After the tournament, return all participants to the original population pool.

---
### **Assignment**
Implement the `tournament_selection` function following the steps outlined above and as discussed in the lecture. For this function, we assume that the fitness of each solution is already evaluated, stored in the array `fitness` and to our function as attribute. `population` follows the definition from the previous step and `tournament_size` is a simple integer number specifying the number of competing solutions.

### **Hints**
- Shape Adjustment: Ensure that the selected individual's data structure is correctly formatted for subsequent processing. For instance, if you have an array of shape `(12,)`, it should be reshaped to `(1, 12)` to maintain consistency in data handling. This can be accomplished using:

```python
reshaped_array = array.reshape(1, -1)
```
This ensures that the selected individual is compatible with the rest of the algorithm's operations.

---

In [26]:
def tournament_selection(population, fitness, tournament_size):
    best_individual_from_tournamet = ...
    return best_individual_from_tournamet

In [27]:
# Solution 1:
def tournament_selection(population, fitness, tournament_size):
    indices_list = np.random.choice(len(population), tournament_size, replace=False)
    chosen_parents = np.array([population[i] for i in indices_list])
    parent_fitnesses = np.array([fitnesses[i] for i in indices_list])
    max_fitness_idx = np.argmax(parent_fitnesses)

    return chosen_parents[max_fitness_idx].reshape(1, -1)

In [28]:
# Solution 2:
def tournament_selection(population, fitnesses, tournament_size):
    # Choose tournament participants
    indices = np.random.choice(population.shape[0], tournament_size, replace=False)
    
    # Evaluate winner
    contenders_fitness = fitnesses[indices]
    max_contenders_fitness_index = np.argmax(contenders_fitness)
    winner_index = indices[max_contenders_fitness_index]
    
    winner = population[winner_index,:]
    
    return winner.reshape(1, -1)

In [29]:
# Test your function
population_size = 8
chromosome_length = 12

population = np.random.randint(0, 2, size=(population_size, chromosome_length))
fitness = np.random.uniform(size=(population_size,))
tournament_size = 8 # we can only test for the full population, otherwise you need to add prints in your function.

winner = tournament_selection(population, fitness, tournament_size)

print(f"Fitness:\n{fitness} at {np.argmax(fitness)}")
print(f"Population:\n{population}")

index = search_index_in_columns(population, winner)
print(f"Tournament winner: {winner} at {index}")
print(f"Tournament winner shape: {winner.shape}")

Fitness:
[0.7041 0.8139 0.0147 0.4822 0.7898 0.579  0.6071 0.2967] at 1
Population:
[[1 1 1 0 0 1 0 1 1 1 0 1]
 [0 0 0 0 1 1 1 1 0 1 1 0]
 [0 1 1 1 1 0 1 0 1 0 1 0]
 [0 0 1 1 0 0 1 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 0 0 1 0]
 [1 1 1 0 0 1 0 0 0 1 0 1]
 [0 0 1 1 0 0 0 0 1 0 0 1]
 [1 1 0 1 1 0 0 1 0 1 1 1]]
Tournament winner: [[0 0 0 0 1 1 1 1 0 1 1 0]] at 1
Tournament winner shape: (1, 12)


## Step 4a: Crossover

Crossover is a process inspired by natural reproduction, allowing for the recombination of genetic material to create new offspring. In this step, we'll implement a simple one-point reciprocal crossover.

<img src="assets/one-point-crossover.png" width="550">

---
### **Assignment**
Implement the `stochastic_one_point_crossover`-function to perform a one-point crossover on chromosomes.
1. **Select a Crossover Point:** Choose a random index `idx` along the chromosome that will serve as the point for slicing and recombining the genetic material.
2. **Recombine to form new chromosomes:** Use the chosen index to interchange segments between two chromosomes, producing two unique offspring, as depicted in the provided figure.
3. **Introduce Stochastic Crossover:** Implement a probability check for performing the crossover, determined by a `cross_probability` parameter. If a randomly generated number is lower than this probability, the crossover is skipped, and the original parents are returned unchanged as children. If the number is higher, proceed with the crossover.

`parent_1` and `parent_2` stores each the parameter / genotype vector as 1D array. `cross_probability` is a float number between 0 and 1 $[0, 1]$. 

### **Hint**

- **Slicing Arrays:** Use NumPy's indexing to slice arrays. For a single dimension:

```python
array_slice = array_1[0:index]
```
When dealing with multi-dimensional data, such as column vectors, specify the row and column for slicing:

```python
array_slice = array_1[0, 0:index]
```

- **Merging Slices:** Combine two slices using `np.concatenate` or `np.hstack`. `np.vstack` is not suitable for this operation.
- **Debugging Tips:** Insert print statements to debug your function. Ensure to remove these once your code functions correctly to maintain clean and efficient code execution.

---

In [30]:
def stochastic_one_point_crossover(parent_1, parent_2, cross_probability):
    ...

In [31]:
# Solution 1:
def stochastic_one_point_crossover(parent_1, parent_2, crossover_probability):
    if np.random.rand() < crossover_probability:
        idx = np.random.randint(1, parent_1.shape[1])
        
        child_1 = np.concatenate((parent_1[0, :idx], parent_2[0, idx:]))
        child_2 = np.concatenate((parent_2[0, :idx], parent_1[0, idx:]))
        
        return child_1, child_2
    else:
        child_1 = parent_1
        child_2 = parent_2
        
        return child_1, child_2

In [32]:
# Solution 2:
def stochastic_one_point_crossover(parent_1, parent_2, crossover_probability):
    if np.random.rand() >= crossover_probability:
        return parent_1, parent_2
    
    idx = np.random.randint(low=1, high=parent_1.shape[1])
    
    child_1 = np.concatenate((parent_1[0, :idx], parent_2[0, idx:]))
    child_2 = np.concatenate((parent_2[0, :idx], parent_1[0, idx:]))
    
    child_1 = child_1.reshape(1, -1)
    child_2 = child_2.reshape(1, -1)
    
    return child_1, child_2

In [33]:
# Test your function:
chromosome_length = 6
crossover_probability = 1.0

parent_1 = np.random.randint(0, 2, size=(1, chromosome_length))
parent_2 = np.random.randint(0, 2, size=(1, chromosome_length))

child_1, child_2 = stochastic_one_point_crossover(parent_1, parent_2, crossover_probability)

print(f"Parent 1: {parent_1}\nParent 2: {parent_2}\n")
print(f"Child 1: {child_1}\nChild 2: {child_2}\n")

print(f"Parent 1 shape: {parent_1.shape}\nParent 2 shape: {parent_2.shape}\n")
print(f"Child 1 shape: {child_1.shape}\nChild 2 shape: {child_2.shape}\n")

Parent 1: [[0 1 1 1 1 1]]
Parent 2: [[0 1 0 0 1 1]]

Child 1: [[0 1 1 1 1 1]]
Child 2: [[0 1 0 0 1 1]]

Parent 1 shape: (1, 6)
Parent 2 shape: (1, 6)

Child 1 shape: (1, 6)
Child 2 shape: (1, 6)



## Step 4b: Mutation

Mutation plays a critical role in the process of evolution, introducing variations in the genes of organisms, which can be triggered by environmental factors. These genetic alterations are key to exploring new solutions and enhancing diversity within a population.

---
### **Assignment**
Implement the function `mutate_genotypes` to introduce mutations within the offspring population. Similar to crossover, introduce a probability that mutation appears. However, we decide individually for each gene of each population member if it mutates with `mutation_probability`.

`population` follows the previous definition and is a 2D array. `mutation_probability` is a float number between 0 and 1 $[0,1]$.

---

In [34]:
def mutate_genotypes(population, mutation_probability):
    ...

In [35]:
# Solution 1:
def mutate_genotypes(population, mutation_probability):
    mutated_population = population.copy()

    for i in range(len(population)):
        for j in range(len(population[i])):
            if np.random.rand() < mutation_probability:
                if mutated_population[i][j] == 0:
                    mutated_population[i][j] = 1
                else:
                    mutated_population[i][j] = 0

    return mutated_population

In [36]:
# Solution 2:
def mutate_genotypes(population, mutation_probability):
    # Create a boolean mask where True indicates potential mutation sites
    mutation_mask = np.random.rand(*population.shape) < mutation_probability
    
    # Flip the bits where the mask is True
    mutated_population = population ^ mutation_mask

    return mutated_population

In [37]:
# Test your function:
mutation_probability = 0.05
population_size = 10
chromosome_length = 15

population = np.random.randint(0, 2, size=(population_size, chromosome_length))

mutated_population = mutate_genotypes(population, mutation_probability)

print(f"Original population:\n{population}\n")
print("Mutated population:")
highlight_mutations(population, mutated_population)
print("--> (mutations are highlighted)")

Original population:
[[1 1 0 0 1 1 1 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 1 1 1 0 0 1 1 0 0 1]
 [0 0 0 1 1 1 1 0 1 0 1 1 1 0 0]
 [1 1 1 0 1 0 0 0 0 1 1 0 1 0 1]
 [1 0 0 1 0 1 0 1 1 0 1 1 0 0 0]
 [0 0 1 1 0 0 1 1 0 1 0 1 1 0 1]
 [0 0 0 0 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 0 1 1 0 0 0 0 0 1 0 1 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 1 0 1 1]
 [1 1 1 0 1 1 0 1 0 1 0 0 1 1 0]]

Mutated population:
[[1 1 0 1 0 1 1 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 1 1 1 0 0 1 1 0 0 1]
 [0 0 0 1 1 1 1 0 1 0 1 1 1 0 0]
 [1 1 1 0 1 0 0 0 0 0 1 0 1 0 1]
 [1 0 1 1 0 1 0 1 1 0 1 1 0 0 0]
 [0 0 1 1 0 0 1 1 0 1 0 1 1 0 1]
 [0 0 0 0 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 0 0 1 0 0 1 0 0 1 0 1 1 0]
 [0 1 0 1 1 1 0 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 1 0 1 0 1 0 0 1 1 0]]
--> (mutations are highlighted)
